services:
  tueri_api:
    build:
      context: ..
      dockerfile: tueri_api/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - AUTH_TOKEN=example-auth-token
      - LOG_LEVEL=DEBUG
      - APP_WORKERS=1
      - SCAN_FAIL_FAST=true
      - LAZY_LOAD=true
      - MONGODB_URL=mongodb://root:example@host.docker.internal:27017/
      - MONGO_DB=ChatApp
      - MONGO_COLLECTION=TueriScanners
      # - CACHE_MAX_SIZE=1000
      # - CACHE_TTL=3600
    restart: unless-stopped
    volumes:
      - ./config/app_config.yml:/home/user/app/config/app_config.yml
